### ISSUE TITLE
Hide cheat sheet

### ISSUE THREAD

**Issue by gseaton** [bodil/catnip#17]
It would be great to hide the cheat sheet.

Maybe there's a way now, but I haven't found it in the docs.

Also, if you hid the cheat sheet, it would be great to have ALL of the possible commands accessible via menus.

Great project.

**Comment by Dimagog** [comment]
Cheat sheet itself says that Ctrl-1 hides it.

**Comment by gseaton** [comment]
You're right, CTRL-1 hides the cheat sheet.

The verbiage is actually 'Toggle browser frame' which isn't all that descriptive but, yes, the cheat sheet is hidden.
