### ISSUE TITLE
Be able to set port for Catnip server

### ISSUE THREAD

**Issue by gseaton** [bodil/catnip#18]
If someone wants to run the Catnip server in the background (as a daemon on start-up), there seems to be no way to set the port number for the Catnip server.

The current behavior is that it appears to run on random port numbers which make it impossible to configure a front-end web server proxy to forward the requests.

Non-standard ports are blocked by many firewalls so putting the Catnip server behind a web proxy allows for access via the standard HTTP port (80).

**Comment by Dimagog** [comment]
To allow adding more parameters in the future and to be consistent with other lein plugins the params should look like a map.
I.e. `lein edit`<b>`:port`</b> `8888`
