### ISSUE TITLE
Allow remote access to Catnip server

### ISSUE THREAD

**Issue by gseaton** [bodil/catnip#19]
The Catnip server appears to use 'localhost' as the host name.

This behavior makes any reference to the server not using 'localhost' fail and makes it not possible to connect from a remote machine. 

For example, if the host name is 'foobar' then the call to 'http://localhost:{catnip-listen-port}' works (if you're on the same machine as the Catnip server) but the call to 'http://foobar:{catnip-listen-port}' fails (even if you're on the same machine as the Catnip server).

**Comment by gseaton** [comment]
I know there might be a security question on this, but here's the scenario for which I (and maybe others) would like to use Catnip 

Scratch Clojure Environment : Allow a scratch environment to test out Clojure code anywhere on the Internet or enterprise network AND retain those files.  You can lock down access via a front-end proxy and/or firewall.  This also would allow for Clojure source files with best practices / idiomatic Clojure code to be made available (as runnable code) to the developer team.

**Comment by bodil** [comment]
Yeah, there's a very big security question - implementing this would be a little insane. There's also an easy workaround if you really want to do this anyway (which, in your use case, given a trusted local network, wouldn't be quite so insane): just set up an HTTP proxy on the machine Catnip is running on. Of course, this requires issue #18 to be dealt with first, which I'll look into soonish. Closing this one, however.

**Comment by bodil** [comment]
By the way, if you should find Catnip's client code has issues about not being on localhost, feel free to report those.
